language: ruby
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^jruby- && ! $TRAVIS_RUBY_VERSION =~ ^jruby-(1|9\.[01]\.) ]]; then export JRUBY_OPTS=`echo "$JRUBY_OPTS" | sed -E -e 's/--((no)?client|server)//g'`; fi
  - if [[ $TRAVIS_RUBY_VERSION =~ ^jruby- ]]; then echo "JRUBY_OPTS=$JRUBY_OPTS"; fi
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-(1|9\.0))\. ]]; then gem install rubygems-update --version '~> 2.7' --no-document && update_rubygems; elif [[ ! $TRAVIS_RUBY_VERSION =~ ^truffleruby- ]]; then gem update --system --no-document; fi
  - gem --version
  - if [[ $TRAVIS_RUBY_VERSION =~ ^(1|2\.[012]|jruby-(1|9\.0))\. ]]; then gem install bundler --version '~> 1.17' --no-document; else gem install bundler --no-document; fi
  - bundle --version
before_script:
  - bundle update
cache: bundler
env:
  global:
    - TESTOPTS=--verbose
jobs:
  include:
    - rvm: 1.9.3-p551
      dist: trusty
    - rvm: 2.0.0-p648
      dist: trusty
    - rvm: 2.1.10
      dist: trusty
    - rvm: 2.2.10
      dist: trusty
    - rvm: 2.3.8
      dist: bionic
    - rvm: 2.4.10
      dist: focal
    - rvm: 2.5.8
      dist: focal
    - rvm: 2.6.6
      dist: focal
    - rvm: 2.7.2
      dist: focal
    - rvm: ruby-head
      dist: focal
    - rvm: jruby-1.7.27
      dist: trusty
    - rvm: jruby-9.0.5.0
      dist: trusty
    - rvm: jruby-9.1.17.0
      dist: focal
    - rvm: jruby-9.2.14.0
      dist: focal
    - rvm: jruby-head
      dist: focal
    - rvm: truffleruby-20.3.0
      dist: focal
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-20.3.0
